CREATE TABLE produit (
IdProduit NUMBER (11,0) NOT NULL,
NomProduit VARCHAR2(60)  NOT NULL,
CodeProduit NUMBER(11,0)  NOT NULL,
DescProduit VARCHAR2(60)  NOT NULL,
EtatProduit VARCHAR2(60)  NOT NULL,
CONSTRAINT PK_PRODUIT PRIMARY KEY () USING INDEX TABLESPACE VB_Mesguen_Index
) TABLESPACE VB_Mesguen_Data ;